language: php
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

_envs:
  - &stage_test
    before_install:
      - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
    before_script:
      - export PATH="$HOME/.composer/vendor/bin:$PATH"
      - composer global require "phpunit/phpunit:^7"
      - composer install
    script:
      - phpunit

jobs:
  fast_finish: true
  include:
    - stage: lint
      before_script:
        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - composer global require "squizlabs/php_codesniffer:^3"
      php: 7.2
      script:
        - phpcs

    - stage: test
      php: 7.1
      <<: *stage_test

    - stage: test
      php: 7.2
      <<: *stage_test

    - stage: test
      php: 7.3
      <<: *stage_test

    - stage: test
      php: 7.4
      <<: *stage_test

    - stage: coverage
      php: 7.2
      <<: *stage_test
      before_install: skip
      after_script:
        - bash <(curl -s https://codecov.io/bash)
